management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,refresh
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}