server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/microservices-realm
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: clientes-cuentas-clientes
          uri: lb://clientes-cuentas-microservicio
          predicates:
            - Path=/api/clientes/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/v1/clientes-cuentas/${segment}
        - id: clientes-cuentas-cuentas
          uri: lb://clientes-cuentas-microservicio
          predicates:
            - Path=/api/cuentas/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/v1/clientes-cuentas/${segment}
        - id: clientes-cuentas-movimientos
          uri: lb://clientes-cuentas-microservicio
          predicates:
            - Path=/api/movimientos/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/v1/clientes-cuentas/${segment}
        - id: audit-service
          uri: lb://audit-service
          predicates:
            - Path=/api/audit/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/v1/audit/${segment}
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
