spring:
  application:
    name: clientes-cuentas-microservicio
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      profile: dev
      label: feature/account-movements-history