DROP TABLE IF EXISTS CUENTA_BANCARIA;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS MOVIMIENTO;

CREATE TABLE CLIENTE (
    DNI VARCHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(100),
    APELLIDO1 VARCHAR(100),
    APELLIDO2 VARCHAR(100),
    FECHA_NACIMIENTO DATE
);

CREATE TABLE CUENTA_BANCARIA (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DNI_CLIENTE VARCHAR(20) NOT NULL,
    TIPO_CUENTA VARCHAR(50) NOT NULL,
    TOTAL DOUBLE NOT NULL,
    CONSTRAINT FK_CLIENTE_CUENTA FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE (DNI)
);

CREATE TABLE MOVIMIENTO (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUENTA_ID BIGINT NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    IMPORTE DECIMAL(15, 2) NOT NULL,
    CREATE_AT DATE NOT NULL DEFAULT CURRENT_DATE,
    DESCRIPCION VARCHAR(255),

    CONSTRAINT fk_MOVIMIENTO_CUENTA_BANCARIA
        FOREIGN KEY (CUENTA_ID)
        REFERENCES CUENTA_BANCARIA(ID)
);