DROP TABLE IF EXISTS CUENTA_BANCARIA;
DROP TABLE IF EXISTS CLIENTE;

CREATE TABLE CLIENTE (
    DNI VARCHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR(100),
    APELLIDO1 VARCHAR(100),
    APELLIDO2 VARCHAR(100),
    FECHA_NACIMIENTO DATE
);

CREATE TABLE CUENTA_BANCARIA (
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    DNI_CLIENTE VARCHAR(20) NOT NULL,
    TIPO_CUENTA VARCHAR(50) NOT NULL,
    TOTAL DOUBLE NOT NULL,
    CONSTRAINT FK_CLIENTE_CUENTA FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE (DNI)
);