FROM eclipse-temurin:21-jre

WORKDIR /app

# Copiamos el JAR generado por Maven desde el módulo del Config Server
COPY ./clientes-cuentas-microservicio-config-server/target/*.jar app.jar

EXPOSE 8888

ENTRYPOINT ["java", "-jar", "app.jar"]
