FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY clientes-cuentas-microservicio-gateway/target/clientes-cuentas-microservicio-gateway-*.jar app.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "app.jar"]
