FROM eclipse-temurin:21-jre

WORKDIR /app

COPY clientes-cuentas-microservicio-eureka-server/target/clientes-cuentas-microservicio-eureka-server-*.jar app.jar

EXPOSE 8761

ENTRYPOINT ["java", "-jar", "app.jar"]
