version: "3.9"

services:
  # ============================
  # CONFIG SERVER
  # ============================
  config-server:
    container_name: config-server
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.config
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8888:8888"
    networks:
      - backend-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 10

  # ============================
  # EUREKA SERVER
  # ============================
  eureka-server:
    container_name: eureka-server
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.eureka
    ports:
      - "8761:8761"
    networks:
      - backend-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 10

  # ============================
  # MICROSERVICIO CLIENTES-CUENTAS
  # ============================
  clientes-cuentas-ms:
    container_name: clientes-cuentas-ms
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.micro
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - backend-net
      - docker_platform-net

  # ============================
  # KEYCLOAK + POSTGRES
  # ============================
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command:
      - start
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KC_HOSTNAME: localhost
      KC_PROXY: edge

    ports:
      - "8082:8082"

    depends_on:
      - keycloak-postgres

    volumes:
      - keycloak_export:/opt/keycloak/data
      - keycloak_conf:/opt/keycloak/conf
      - keycloak_providers:/opt/keycloak/providers

    networks:
      - backend-net

  keycloak-postgres:
    image: postgres:15
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    networks:
      - backend-net

  # ============================
  # API GATEWAY
  # ============================
  gateway-ms:
    container_name: gateway-server
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_started
    networks:
      - backend-net

# ============================
# VOLUMENES
# ============================
volumes:
  keycloak_db:
  keycloak_export:
  keycloak_conf:
  keycloak_providers:

# ============================
# RED
# ============================
networks:
  backend-net:
    driver: bridge
  docker_platform-net:
    external: true
